#!/usr/bin/env python3
"""Regenerate src/llama-draft-vocab-latin.h from the ranked shortlist JSON.

usage: gen_draft_vocab_latin.py [shortlist.json] [out.h]

The shortlist is the frequency-ranked Latin subset of the Qwen3.8-Flash-Next vocabulary produced by
harness/_rank_shortlist.py (10.6M-token / 32.4 MB Latin corpus, 32492 frequent tokens + all 276
control tokens force-included). It is corpus-derived, NOT derivable from the model file, so it is
baked into the binary rather than shipped as a data file the launcher would have to carry.

The ids are written ascending: that is what lets the load-time trim gather rows with forward-only
seeks, and what makes the resulting d2t mapping monotonic.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_IN = os.path.join(ROOT, "harness", "_shortlist_32k.json")
DEFAULT_OUT = os.path.join(ROOT, "src", "llama-draft-vocab-latin.h")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IN
    dst = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT

    ids = sorted(set(int(x) for x in json.load(open(src))["ids"]))
    assert len(ids) >= 2, "shortlist too small"
    assert all(b > a for a, b in zip(ids, ids[1:])), "ids must be strictly ascending"
    assert max(ids) < 248320, "id out of range for the Qwen3.8-Flash-Next vocabulary"

    out = []
    out.append("// GENERATED by tools/gen_draft_vocab_latin.py -- do not edit by hand.")
    out.append("// Source: harness/_shortlist_32k.json (ranked by harness/_rank_shortlist.py).")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("// Frequency-ranked Latin shortlist of the Qwen3.8-Flash-Next vocabulary (vocab 248320):")
    out.append("// %d frequent tokens ranked on a 10.6M-token Latin corpus + all 276 control tokens." % (len(ids) - 276))
    out.append("// Held-out coverage 99.90% on assistant outputs, 97.97% on English prose; the break-even")
    out.append("// for draft acceptance is ~92.1%. NOT for CJK: Chinese ids sit at 95726-145519 and a Latin")
    out.append("// shortlist covers only ~32% of Chinese text, which makes speculative decoding a net loss.")
    out.append("//")
    out.append("// Ascending, so a trimmed head is a forward-only row gather and d2t is monotonic.")
    out.append("#define LLAMA_DRAFT_VOCAB_LATIN_N %d" % len(ids))
    out.append("static const uint32_t LLAMA_DRAFT_VOCAB_LATIN[LLAMA_DRAFT_VOCAB_LATIN_N] = {")
    for i in range(0, len(ids), 16):
        out.append("    " + " ".join(str(x) + "," for x in ids[i:i + 16]))
    out.append("};")

    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d ids, max %d" % (dst, len(ids), max(ids)))


if __name__ == "__main__":
    main()
